### ISSUE TITLE
Segmentation fault when compiling VGG16

### ISSUE THREAD

**Issue by JunningWu** [nvdla/sw#31]
the prototxt and caffemodel is downloaded from this site:
http://www.robots.ox.ac.uk/%7Evgg/research/very_deep/

when I compile the VGG16 CNN, there is an error:

- nvdla@nvdla:~/NVDLA/git-nvdla-sw/prebuilt/linux$ ./nvdla_compiler --prototxt vgg16/VGG_ILSVRC_16_layers_deploy.prototxt --caffemodel vgg16/VGG_ILSVRC_16_layers.caffemodel -o vgg16
- creating new wisdom context...
- opening wisdom context...
- parsing caffe network...
- Segmentation fault (core dumped)

when debug this using gdb, it shows like this:

- parsing caffe network...
- 
- Program received signal SIGSEGV, Segmentation fault.
- 0x000000000040b34c in parseCaffeNetwork(TestAppArgs const*, TestInfo*) ()
- (gdb) bt
- #0  0x000000000040b34c in parseCaffeNetwork(TestAppArgs const*, TestInfo*) ()
- #1  0x000000000040b984 in parseAndCompile(TestAppArgs const*, TestInfo*) ()
- #2  0x0000000000406abd in launchTest(TestAppArgs const*) ()
- #3  0x0000000000406eea in main ()
- 

since there does not have some NEW features apart from Alexnet or Lenet, this error is very strange.

**Comment by darrenleong** [comment]
i had the same error when compiling vgg16 as JIAWENYANG faced. 
Can nvdla support vgg16?
